language: java
script:
- gradle build
deploy:
  provider: heroku
  api_key:
    secure: tPUOcCkSadwrYeP8E45We1xxHYGrNaGbaVeucwmBE3ylSHJ17oUJTFYP/Eq+HtZzPRTlrj3oy7CVOvw8fN7BWGV0eqCoc/GqrGyd68UTcoLqUnZhVB7oIaMsIQWYm8A24KfAdUGzUc3QVaEhHo3dUR6yGJoex351ha5QtdZ0O4lomcBgmlDTljjbdGPLtv+LKv0/JNZZT5JgltuBA2Ru8YE2xxhfSATH6m7LY7qmcjx1fRlX4r3JxaX0NUwnrY2Sjk2hjshAToMClXz0TdvZWBW40R9w+X2AZMI9EUz9SBNlcU909YWKFoKms5/TEOMLKZbTXu5njsfBhdSRwd6NCUqAOiU+mbD4fuzg2OCoCQDm2aMB/R0uN0kYrYct1WGmNhXfN26tmc6NpOOQyNlDsFesFEmDdp3JMPQEyM6S/1GVAArD5e3x+ze53g/ryu3kz3onqDt+bFtjiSS91E36h3YQK1UHvtj64Y3YPd3KrRJ7BL6xSczMdI2zoK7eXZe9aDqbn7BLQDo9Yx2vWFVJtG+nM9Nm4nLRtjp2aMrqfkL21Y/9O0jlH+92NnH01Ri0bhClzNkB3HLmQYtkWAoctS8qHGze3tqsZ0osxd9VWBTLc2EWrJFqYA7LdwUdFBxOXFNC7mmX2SyiZpCMsDSu2pPzIbnAUHGaqnIRp+uz7X4=
  app: tutorme-ecse321-group3
