language: java
script:
- gradle build
deploy:
  provider: heroku
  api_key:
    secure: fL/VBcUAjoFUpM5GLhAlagT7fzdxsF6cFhz2/Gb6v/Osn0VtflCQdybuQ6jXxPYXrBsL0RULGVd53DNe4uKLiLxkz4S8Z/iA7JynftZmkfl3d7tYZYoPI53XIFotDfE3vKBHHfjm/1eQkCA6tUV4I05jbj3HTalFv3SLrgCBuMu2fQseqIjQwqemXtoau8vK4Dhb5SfbN01HRmcJ/9uNuQ/UwAYdjbv9fg7XCjPTn33pTYj3hb1mPpb+MaPs2U5J6WE4MRPXQ0Q7g0EOWBWcimSNQ7a3rIlqF7jplLHPe1kxEXK1b/O8/mRzTFPdRyFbJaayDWXNjOUkqUbhIEm3tRoYMWcBtRgHytlzKuUStszsa5Ysj/U6iAWtgR+VPtdDNFnKVpoHv6wXLkR1w8eVTNehlZ0K+MBC36MS0g+vHUTN9D2NmKGtL+qi+Jfv5k6zwoDWwI0TQKl3vpFAiMcTvk7h48OD6I/PDWWaC+kx2vFhBLPYBqp8nriYZTZCflMi1PHoslS9EC45Wiri8Y/EFjBTFZSCTmmsyp9mUvXKdPnCfoR9D+Myl0Uf4OxvPMvLovJuDj15gLNtHFsyqKxMmciTfpJ0C4kG4UsbJCgm7EMAwdZFGWXR6UmIzdfmeD8teuNHKwjMAZbgtuL+tQ2qrVZ4AclHLVRXlUQj92m6XJw=
  app: tutorme-ecse321-group3